version: '3.9'

services:
  db-pagamentos:
    container_name: db-pagamentos
    hostname: db-pagamentos
    image: postgres:15.6
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready -U ${DB_USER:-pguser} -d ${DB_NAME:-rms}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME:-pguser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pgpwd}
      POSTGRES_DB: ${DB_NAME:-rms}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: always
    networks:
      - default

  api-pagamentos:
    container_name: api-pagamentos
    hostname: api-pagamentos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    expose:
      - 3000
    env_file:
      - .env
    environment:
      DB_HOST: db-pagamentos
      DB_PORT: 5432
      MONGO_URL: "mongodb://admin:pass@mongo-dev:27017"
      DB_USER: ${DB_USERNAME:-pguser}
      DB_PASSWORD: ${DB_PASSWORD:-pgpwd}
      DB_NAME: ${DB_NAME:-rms}
      DB_SSL: ${DB_SSL:-false}
      ACCESS_TOKEN_MERCADOPAGO: ${ACCESS_TOKEN_MERCADOPAGO:-}
      USER_ID_MERCADOPAGO: ${USER_ID_MERCADOPAGO:-}
      EXTERNAL_POS_ID_MERCADOPAGO: ${EXTERNAL_POS_ID_MERCADOPAGO:-}
      WEBHOOK_URL_MERCADOPAGO: ${WEBHOOK_URL_MERCADOPAGO:-}
      IDEMPOTENCY_KEY_MERCADOPAGO: ${IDEMPOTENCY_KEY_MERCADOPAGO:-a005986e-f97c-4274-91cf-b32d2672824f}
    restart: always
    networks:
      - default
    depends_on:
      - db-pagamentos
  
  mongodb:
    container_name: mongo-dev
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 1024M

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 1024M
networks:
  default:
    driver: bridge

volumes:
  postgres:
