apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-api-pagamentos
  namespace: rms
  labels:
    app: rms-api-pagamentos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rms-api-pagamentos
  template:
    metadata:
      labels:
        app: rms-api-pagamentos
    spec:
      serviceAccountName: aws-iam-serviceaccount # ServiceAccount com Role que permite acesso ao AWS Secrets Manager
      automountServiceAccountToken: false
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secrets-api-pagamentos
      containers:
        - name: rms-api-pagamentos
          image: 900534935988.dkr.ecr.us-east-1.amazonaws.com/rms-api-pagamentos:latest
          envFrom:
            - configMapRef:
                name: rms-api-pagamentos-config
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: db-pagamentos-secret
                  key: host
            - name: ACCESS_TOKEN_MERCADOPAGO
              valueFrom:
                secretKeyRef:
                  name: mercadopago-secret
                  key: ACCESS_TOKEN_MERCADOPAGO
            - name: USER_ID_MERCADOPAGO
              valueFrom:
                secretKeyRef:
                  name: mercadopago-secret
                  key: USER_ID_MERCADOPAGO
            - name: EXTERNAL_POS_ID_MERCADOPAGO
              valueFrom:
                secretKeyRef:
                  name: mercadopago-secret
                  key: EXTERNAL_POS_ID_MERCADOPAGO
            - name: WEBHOOK_URL_MERCADOPAGO
              valueFrom:
                secretKeyRef:
                  name: mercadopago-secret
                  key: WEBHOOK_URL_MERCADOPAGO
            - name: NOME_FILA_NOVA_COBRANCA
              valueFrom:
                secretKeyRef:
                  name: sqs-fila-nova-cobranca-secret
                  key: NOME_FILA_NOVA_COBRANCA
            - name: URL_FILA_NOVA_COBRANCA
              valueFrom:
                secretKeyRef:
                  name: sqs-fila-nova-cobranca-secret
                  key: URL_FILA_NOVA_COBRANCA
            - name: REGION_FILA_NOVA_COBRANCA
              valueFrom:
                secretKeyRef:
                  name: sqs-fila-nova-cobranca-secret
                  key: REGION_FILA_NOVA_COBRANCA
            - name: NOME_FILA_COBRANCA_GERADA
              valueFrom:
                secretKeyRef:
                  name: sqs-fila-cobranca-gerada-secret
                  key: NOME_FILA_COBRANCA_GERADA
            - name: URL_FILA_COBRANCA_GERADA
              valueFrom:
                secretKeyRef:
                  name: sqs-fila-cobranca-gerada-secret
                  key: URL_FILA_COBRANCA_GERADA
            - name: REGION_FILA_COBRANCA_GERADA
              valueFrom:
                secretKeyRef:
                  name: sqs-fila-cobranca-gerada-secret
                  key: REGION_FILA_COBRANCA_GERADA
            - name: NOME_FILA_FALHA_COBRANCA
              valueFrom:
                secretKeyRef:
                  name: sqs-fila-falha-cobranca-secret
                  key: NOME_FILA_FALHA_COBRANCA
            - name: URL_FILA_FALHA_COBRANCA
              valueFrom:
                secretKeyRef:
                  name: sqs-fila-falha-cobranca-secret
                  key: URL_FILA_FALHA_COBRANCA
            - name: REGION_FILA_FALHA_COBRANCA
              valueFrom:
                secretKeyRef:
                  name: sqs-fila-falha-cobranca-secret
                  key: REGION_FILA_FALHA_COBRANCA
          ports:
            - containerPort: 3003
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "0.5"
              memory: "1Gi"
              ephemeral-storage: "2Gi"