apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-api-pagamentos
  namespace: rms
spec:
  provider: aws
  secretObjects:
    - secretName: db-pagamentos-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: host
          key: host
    - secretName: mercadopago-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: ACCESS_TOKEN_MERCADOPAGO
          key: ACCESS_TOKEN_MERCADOPAGO
        - objectName: USER_ID_MERCADOPAGO
          key: USER_ID_MERCADOPAGO
        - objectName: EXTERNAL_POS_ID_MERCADOPAGO
          key: EXTERNAL_POS_ID_MERCADOPAGO
        - objectName: WEBHOOK_URL_MERCADOPAGO
          key: WEBHOOK_URL_MERCADOPAGO
    - secretName: sqs-fila-nova-cobranca-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: NOME_FILA_NOVA_COBRANCA
          key: NOME_FILA_NOVA_COBRANCA
        - objectName: URL_FILA_NOVA_COBRANCA
          key: URL_FILA_NOVA_COBRANCA
        - objectName: REGION_FILA_NOVA_COBRANCA
          key: REGION_FILA_NOVA_COBRANCA
    - secretName: sqs-fila-cobranca-gerada-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: NOME_FILA_COBRANCA_GERADA
          key: NOME_FILA_COBRANCA_GERADA
        - objectName: URL_FILA_COBRANCA_GERADA
          key: URL_FILA_COBRANCA_GERADA
        - objectName: REGION_FILA_COBRANCA_GERADA
          key: REGION_FILA_COBRANCA_GERADA
    - secretName: sqs-fila-falha-cobranca-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: NOME_FILA_FALHA_COBRANCA
          key: NOME_FILA_FALHA_COBRANCA
        - objectName: URL_FILA_FALHA_COBRANCA
          key: URL_FILA_FALHA_COBRANCA
        - objectName: REGION_FILA_FALHA_COBRANCA
          key: REGION_FILA_FALHA_COBRANCA
  parameters:
    # Informe abaixo no campo objectName os nomes dos Segredos do AWS Secrets Manager que deseja acessar.
    # Certifique-se de que as Keys declaradas abaixo existem e estão preenchidas na AWS, caso contrário receberá o erro "Failed to fetch secret from all regions"
    objects: |
      - objectName: "prod/pagamentos/Mongodb"
        objectType: "secretsmanager"
        jmesPath:
          - path: "host"
            objectAlias: "host"
      - objectName: "prod/RMS/MercadoPago"
        objectType: "secretsmanager"
        jmesPath:
          - path: "BASE_URL_API_MERCADOPAGO"
            objectAlias: "BASE_URL_API_MERCADOPAGO"
          - path: "ACCESS_TOKEN_MERCADOPAGO"
            objectAlias: "ACCESS_TOKEN_MERCADOPAGO"
          - path: "USER_ID_MERCADOPAGO"
            objectAlias: "USER_ID_MERCADOPAGO"
          - path: "EXTERNAL_POS_ID_MERCADOPAGO"
            objectAlias: "EXTERNAL_POS_ID_MERCADOPAGO"
          - path: "WEBHOOK_URL_MERCADOPAGO"
            objectAlias: "WEBHOOK_URL_MERCADOPAGO"
      - objectName: "prod/RMS/SQSNovaCobranca"
        objectType: "secretsmanager"
        jmesPath:
          - path: "QUEUE_NAME"
            objectAlias: "NOME_FILA_NOVA_COBRANCA"
          - path: "QUEUE_URL"
            objectAlias: "URL_FILA_NOVA_COBRANCA"
          - path: "QUEUE_REGION"
            objectAlias: "REGION_FILA_NOVA_COBRANCA"
      - objectName: "prod/RMS/SQSCobrancaGerada"
        objectType: "secretsmanager"
        jmesPath:
          - path: "QUEUE_NAME"
            objectAlias: "NOME_FILA_COBRANCA_GERADA"
          - path: "QUEUE_URL"
            objectAlias: "URL_FILA_COBRANCA_GERADA"
          - path: "QUEUE_REGION"
            objectAlias: "REGION_FILA_COBRANCA_GERADA"
      - objectName: "prod/RMS/SQSFalhaCobranca"
        objectType: "secretsmanager"
        jmesPath:
          - path: "QUEUE_NAME"
            objectAlias: "NOME_FILA_FALHA_COBRANCA"
          - path: "QUEUE_URL"
            objectAlias: "URL_FILA_FALHA_COBRANCA"
          - path: "QUEUE_REGION"
            objectAlias: "REGION_FILA_FALHA_COBRANCA"
