apiVersion: v1
kind: Service
metadata:
  name: rms-api-pagamentos
  namespace: rms
  labels:
    app: rms-api-pagamentos
spec:
  selector:
    app: rms-api-pagamentos
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # Porta no Load Balancer
      targetPort: 3003 # Porta do Pod